/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/admissions' | '/classes' | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/admissions' | '/classes' | '/contact'
  id: '__root__' | '/' | '/about' | '/admissions' | '/classes' | '/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
